name: Rust Benchmarks

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0' # Weekly on Sundays

env:
  CARGO_TERM_COLOR: always

jobs:
  benchmarks:
    name: Run Benchmarks
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: nightly
        override: true
        components: rustfmt, clippy
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y libclang-dev
    - name: Run benchmarks
      run: cargo +nightly bench --verbose
    - name: Upload results
      uses: actions/upload-artifact@v3
      with:
        name: benchmark-results
        path: target/criterion
